### ISSUE TITLE
main_QE_consumption.m doesn't replicate Figure 1

### ISSUE THREAD

**Issue by sellingsrud** [cm1518/misspecification#1]
Firstly, main_QE_consumption throws an exception because there are two missing fields in the setup struct, "state_size" and "sample_size". In the file "setup_consumption_QE" those are set to 0, while they are not defined in "setup_QE_consumption" which is the setup called from "main_QE_consumption". Just adding those fields and setting them to zero fails to replicate the posterior plot for omega:

Figure 1 from the paper (p31):
![image](https://user-images.githubusercontent.com/77972591/139827908-e4bae93e-a8e4-443e-9f73-a3b9cb974a08.png)

Figure generated by main_QE_consumption.m

![image](https://user-images.githubusercontent.com/77972591/139828065-5e2c6d8b-cd7e-4c4f-94ac-f1a3598ca5b6.png)

Perhaps those two values, state_size and sample_size needs to be defined to actual values by the user?

**Comment by sellingsrud** [comment]
A bit more info:
- From around the 2500th draw the posterior is either inf or nan and the weights are 1 for the exponential and 0 for everything else from there on out

Plotting only the first 2500 elements of the result object "draws" generates something where the frequency looks a bit off, but qualitatively similar to the figure in the paper:
![image](https://user-images.githubusercontent.com/77972591/139831395-d9e51b86-f102-4531-99e8-c4d7912bb3ee.png)

**Comment by cm1518** [comment]
Thank you for catching this. I have pushed an update that fixes these issues. The changes are as follows:

1. the main file now directly loads the setup structure to avoid any issues
2. It seems the more substantive issue was caused by a draw that returned a NaN posterior value due to numerical issues. Since the original code did not fix the seed we did not encounter this issue when creating the results for the paper. To fix this issue, the updated code now (i) fixes the seed to make results comparable, and (ii) the MH algorithm now automatically checks for a NaN posterior and rejects these draws.

The resulting figure (the eps file is uploaded to ease comparison) is now basically the same as in the main paper (the only difference being due to differences in random seeds).

I have checked the code using Matlab 2020b.
